### ISSUE TITLE
Maven dependencies

### ISSUE THREAD

**Issue by rafaelsakurai** [EmilyBjoerk/gonector#1]
Hi.
For use your maven project, I need to add in my pom.xml your repository:

```
        <repository>
            <snapshots>
                    <enabled>false</enabled>
            </snapshots>
            <id>bintray-maven</id>
            <name>bintray</name>
            <url>https://dl.bintray.com/emilybjoerk/lisoft/</url>
        </repository>
```

Can you add this information in your README.md?

And your project have dependency with log4j-api e log4j-core, that I need to put as dependency of my pom.xml, after that, I can compile the project using your maven project.

Can you change the pom.xml of gonector to include this two dependencies? Maybe with this I do not need to include two dependencies in my pom.xml.

Thank you.

**Comment by EmilyBjoerk** [comment]
The package is available from jcentral, that's all you should need to add...
