### ISSUE TITLE
Scoring

### ISSUE THREAD

**Issue by rafaelsakurai** [EmilyBjoerk/gonector#2]
Hi.

I know that is not mandatory, but can you add a method for "final_score" command?

Thank you.

**Comment by EmilyBjoerk** [comment]
Can you build from source and try it out? I don't have a bot that can score that I can test with but I have implemented the command as per the gtp spec. It should work but I'd rather not push out an actual release before it's been tested with an actual client program hooked up to it. 

I will leave for a vacation tomorrow so I can't really do anything more right now.

**Comment by rafaelsakurai** [comment]
Hi, thank you for the changes in the source code.

I'm creating a bot, but don't have a right score, I just have an estimated score. I will try with the source code, i think will work.

Maybe in the future, if I have time, I try to create a score for your random bot.

Thank you, enjoy your vacation.

**Comment by barrybecker4** [comment]
I noticed that canScore and getScore were added to the project in git, but the 1.0.0 version released on jcenter does not have it. I don't suppose that a new 1.0.1 (or 1.1.0) version could be released that includes this change?

**Comment by EmilyBjoerk** [comment]
It could, frankly it was so long ago I did this that I don't remember how... I'll see if I can figure it out

**Comment by EmilyBjoerk** [comment]
A new release should be available now.

https://bintray.com/emilybjoerk/lisoft/gonector/1.1.1

**Comment by barrybecker4** [comment]
Thanks! It worked.
I am using this library in https://github.com/barrybecker4/ScalphaGoZero
